name: PR DuneAI Summary

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  summarize-pr:
    name: Summarize PR Using DuneAI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Node Dependencies
        run: npm install

      - name: Summarize PR
        run: npm run summarize-changes